CREATE TABLE IF NOT EXISTS `collections` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `MOVIE_DB_ID` int(11) NOT NULL,
 `NAME` varchar(200) NOT NULL,
 `OVERVIEW` varchar(2000) DEFAULT NULL,
 `CATEGORY` varchar(100) NOT NULL, 
 PRIMARY KEY (`ID`),
 UNIQUE KEY `MOVIE_DB_ID_Category` (`MOVIE_DB_ID`,`CATEGORY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8