CREATE TABLE IF NOT EXISTS `show_episodes` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `SHOW_ID` int(11) NOT NULL,
 `SEASON_NO` int(11) NOT NULL,
 `EPISODE_NO` int(11) NOT NULL,
 `TITLE` varchar(200) NOT NULL,
 `DESCRIPTION` varchar(4000) DEFAULT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8